"""add media fields

Revision ID: 527a6ec8fd3c
Revises: 867f34eef85b
Create Date: 2026-01-28 16:50:26.485781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527a6ec8fd3c'
down_revision = '867f34eef85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('fecha',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('media_url')
        batch_op.drop_column('media_path')

    # ### end Alembic commands ###
