"""add media fields to news

Revision ID: 867f34eef85b
Revises: 16c9983194c0
Create Date: 2026-01-28 12:20:44.758692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867f34eef85b'
down_revision = '16c9983194c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
